# Generated by Django 5.2.1 on 2025-06-03 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_classification_book_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.classification'),
        ),
    ]
